### ISSUE TITLE
Use a Reverse Proxy To Secure And Boost Performance

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/www.spee.ch#40]
## CloudFlare

CloudFlare provides **content delivery network** services, **DDoS** mitigation, Internet **security** and distributed domain name server services, sitting between the visitor and the Cloudflare user's hosting provider, acting as a **reverse proxy** for websites.

[![image](https://user-images.githubusercontent.com/29914179/42417755-3ec67dae-82d5-11e8-9653-5e856bd1e0cf.png) 
![image](https://user-images.githubusercontent.com/29914179/42417793-38442534-82d6-11e8-8a6a-7509c046db3a.png)
 ![image](https://user-images.githubusercontent.com/29914179/42417720-69ee34d2-82d4-11e8-8d9e-79f3d0e130cf.png) ![image](https://user-images.githubusercontent.com/29914179/42417717-461f4dd4-82d4-11e8-87c3-9d5a2b3b7bce.png)](https://api.cloudflare.com/#getting-started-endpoints)

**Comment by tzarebczan** [comment]
Believe we recently added cloud flare, but Bill can confirm.

**Comment by billbitt** [comment]
confirm!
